version: "2.0"
services:
 omnisportdb:
  image: mwdf/omnisportdb
  ports:
   - "5432:5432"
 omnisportweb:
  image: mwdf/omnisportweb
  depends_on:
   - omnisportdb
  environment:
   - OMNISPORT_DBCONN=omnisportdocker_omnisportdb_1:5432/omnisport
   - OMNISPORT_DBUSER=postgres
   - OMNISPORT_DBPW=postgres
   - OMNISPORT_APIURL=omnisportdocker_omnisportweb_1:8080/api
   - OMNISPORT_APICLIENT=Marijn-Willem
   - OMNISPORT_APIPW=M2U
   - OMNISPORT_FILELOC=/usr/tmp
  ports:
   - "8080:8080"