services:
 memcached:
  image: memcached
  container_name: memcached
  ports:
   - "11212:11211"
 omnisportdb:
  image: mwdf/omnisportdb
  container_name: omnisportdb
  ports:
   - "5433:5432"
 omnisportweb:
  image: mwdf/omnisportweb
  container_name: omnisportweb
  depends_on:
   - memcached
   - omnisportdb
  environment:
   - OMNISPORT_DBCONN=omnisportdb:5432/omnisport
   - OMNISPORT_DBUSER=postgres
   - OMNISPORT_DBPW=postgres
   - OMNISPORT_APIURL=http://omnisportweb:8080/api
   - OMNISPORT_APICLIENT=Marijn-Willem
   - OMNISPORT_APIPW=M2U
   - OMNISPORT_FILELOC=/usr/tmp
   - OMNISPORT_MEMHOST=memcached
   - OMNISPORT_MEMPORT=11211
  ports:
   - "8081:8080"