version: "2.0"
services:
 memcached:
  image: memcached
  container_name: memcached
  ports:
   - "11212:11211"
 omnisportdb:
  image: mwdf/omnisportdb/sqlserver
  container_name: omnisportdb
  ports:
   - "1433:1433"
 omnisportweb:
  image: mwdf/omnisportweb
  container_name: omnisportweb
  depends_on:
   - memcached
   - omnisportdb
  environment:
   - OMNISPORT_DBCONN=omnisportdb:1433;database=omnisport
   - OMNISPORT_DBUSER=sa
   - OMNISPORT_DBPW=1234ABcd
   - OMNISPORT_DBTYPE=sqlserver
   - OMNISPORT_APIURL=http://omnisportweb:8080/api
   - OMNISPORT_APICLIENT=Marijn-Willem
   - OMNISPORT_APIPW=M2U
   - OMNISPORT_FILELOC=/usr/tmp
   - OMNISPORT_MEMHOST=memcached
   - OMNISPORT_MEMPORT=11211
  ports:
   - "8081:8080"