services:
 omnisportdbssrv:
  image: mwdf/omnisportdb-sqlserver
  container_name: omnisportdbssrv
  ports:
   - "1433:1433"
 omnisportweb:
  image: mwdf/omnisportweb
  container_name: omnisportweb
  depends_on:
   - omnisportdbssrv
  environment:
   - OMNISPORT_DBCONN=omnisportdbssrv:1433;database=omnisport
   - OMNISPORT_DBUSER=sa
   - OMNISPORT_DBPW=!234ABcd
   - OMNISPORT_DBTYPE=sqlserver
   - OMNISPORT_APIURL=http://omnisportweb:8080/api
   - OMNISPORT_APICLIENT=Marijn-Willem
   - OMNISPORT_APIPW=M2U
   - OMNISPORT_FILELOC=/usr/tmp
   - OMNISPORT_MEMHOST=memcached
   - OMNISPORT_MEMPORT=11211
  ports:
   - "8081:8080"
